"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LAST_PROCESSED_BLOCK_HASH_KEY = exports.LAST_PROCESSED_BLOCK_NUMBER_KEY = exports.LAST_FETCHED_BLOCK_HASH_KEY = exports.LAST_FETCHED_BLOCK_NUMBER_KEY = exports.EVENTS_MODEL_TABLE_NAME = exports.INVALID_CONFIRMATION_EVENT_NAME = exports.NEW_CONFIRMATION_EVENT_NAME = exports.PROGRESS_EVENT_NAME = exports.REORG_OUT_OF_RANGE_EVENT_NAME = exports.REORG_EVENT_NAME = exports.NEW_BLOCK_EVENT_NAME = exports.NEW_EVENT_EVENT_NAME = void 0;
exports.NEW_EVENT_EVENT_NAME = 'newEvent';
exports.NEW_BLOCK_EVENT_NAME = 'newBlock';
exports.REORG_EVENT_NAME = 'reorg';
exports.REORG_OUT_OF_RANGE_EVENT_NAME = 'reorgOutOfRange';
exports.PROGRESS_EVENT_NAME = 'progress';
exports.NEW_CONFIRMATION_EVENT_NAME = 'newConfirmation';
exports.INVALID_CONFIRMATION_EVENT_NAME = 'invalidConfirmation';
exports.EVENTS_MODEL_TABLE_NAME = 'web3events_event';
exports.LAST_FETCHED_BLOCK_NUMBER_KEY = 'lastFetchedBlockNumber';
exports.LAST_FETCHED_BLOCK_HASH_KEY = 'lastFetchedBlockHash';
exports.LAST_PROCESSED_BLOCK_NUMBER_KEY = 'lastProcessedBlockNumber';
exports.LAST_PROCESSED_BLOCK_HASH_KEY = 'lastProcessedBlockHash';
